# Generated by Django 5.2.8 on 2025-11-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_alter_todo_deadline_alter_todo_finishe_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="finishe_at",
            new_name="finished_at",
        ),
    ]
