# Generated by Django 5.2.8 on 2025-11-22 05:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_rename_finishe_at_todo_finished_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContatoComentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("mensagem", models.TextField()),
                ("data_envio", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Comentário de Contato",
                "verbose_name_plural": "Comentários de Contato",
                "ordering": ["-data_envio"],
            },
        ),
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["deadline"]},
        ),
    ]
