# Generated by Django 5.2.8 on 2025-12-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_contatocomentario_alter_todo_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuiaDica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "tipo",
                    models.CharField(
                        choices=[("R", "Raça"), ("D", "Dica")],
                        default="RAÇA",
                        max_length=4,
                        verbose_name="Tipo de Conteúdo",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição/Conteúdo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Conteúdo de Guia/Dica",
                "verbose_name_plural": "Conteúdos de Guia/Dica",
                "ordering": ["-criado_em"],
            },
        ),
    ]
