# Generated by Django 5.2.8 on 2025-12-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0005_guiadica"),
    ]

    operations = [
        migrations.AddField(
            model_name="guiadica",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="guias_dicas/", verbose_name="Imagem"
            ),
        ),
    ]
